# Generated by Django 4.1 on 2022-08-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catalog',
        ),
    ]
