# Generated by Django 4.1 on 2022-08-29 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_rename_category_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='ctg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg.catalog'),
        ),
    ]
