# Generated by Django 4.1 on 2022-08-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_brand_ctg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='ctg',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='ctg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg.catalog'),
        ),
    ]
