# Generated by Django 4.1 on 2022-09-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_remove_brand_ctg_subcategory_ctg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='ctg',
        ),
    ]
