# Generated by Django 4.1 on 2022-11-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0006_subcategory_ctg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
    ]
