# Generated by Django 4.1 on 2022-11-02 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0007_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
